import { DetailRow } from "./DetailRow";
import { SectionCard } from "./SectionCard";
import { StatusBadge } from "./StatusBadge";
import { formatDate, formatDateTime } from "./formatters";

function Toolbar() {
  return (
    <div className="toolbar no-print">
      <button className="toolbar-button" onClick={() => window.print()} type="button">
        Print document
      </button>
    </div>
  );
}

export function AuthPrintPage({ documentData }) {
  const { organization, metadata, subject, authStatus, accessSummary, auditTrail, disclaimer } =
    documentData;

  return (
    <main className="page-root">
      <Toolbar />

      <article className="print-sheet" aria-label="Authentication print record">
        <header className="page-header">
          <div>
            <p className="brand">{organization.name}</p>
            <h1 className="page-title">{organization.subtitle}</h1>
          </div>
          <div className="header-meta">
            <p>Document ID: {metadata.documentId}</p>
            <p>Generated: {formatDateTime(metadata.generatedAt)}</p>
            <p>Generated By: {metadata.generatedBy}</p>
            <p>Environment: {metadata.environment}</p>
          </div>
        </header>

        <div className="section-grid">
          <SectionCard title="Member Identity">
            <dl className="detail-list">
              <DetailRow label="Full Name" value={subject.fullName} />
              <DetailRow label="Member ID" value={subject.memberId} />
              <DetailRow label="Date of Birth" value={formatDate(subject.dateOfBirth)} />
              <DetailRow label="Email" value={subject.email} />
              <DetailRow label="Phone" value={subject.phone} />
            </dl>
          </SectionCard>

          <SectionCard title="Authentication Status">
            <dl className="detail-list">
              <DetailRow label="Status" value={<StatusBadge label={authStatus.level} />} />
              <DetailRow label="Method" value={authStatus.method} />
              <DetailRow
                label="Last Validated"
                value={formatDateTime(authStatus.lastValidatedAt)}
              />
              <DetailRow label="Valid Until" value={formatDateTime(authStatus.expiresAt)} />
            </dl>
          </SectionCard>
        </div>

        <SectionCard title="Access Summary">
          <table className="data-table" aria-label="Access summary table">
            <thead>
              <tr>
                <th scope="col">Service</th>
                <th scope="col">Role</th>
                <th scope="col">Status</th>
              </tr>
            </thead>
            <tbody>
              {accessSummary.map((entry) => (
                <tr key={entry.service}>
                  <td>{entry.service}</td>
                  <td>{entry.role}</td>
                  <td>
                    <StatusBadge label={entry.status} />
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </SectionCard>

        <SectionCard title="Audit Trail">
          <ul className="audit-list">
            {auditTrail.map((entry) => (
              <li key={`${entry.timestamp}-${entry.event}`} className="audit-item">
                <p className="audit-time">{formatDateTime(entry.timestamp)}</p>
                <p className="audit-event">{entry.event}</p>
                <p className="audit-actor">Actor: {entry.actor}</p>
              </li>
            ))}
          </ul>
        </SectionCard>

        <footer className="page-footer">
          <p>{disclaimer}</p>
        </footer>
      </article>
    </main>
  );
}
